"""Build cl/main.tex (Computational Linguistics, clv2025) from ../main.tex.

    python cl/gerar_cl.py

The body is taken verbatim from the generic manuscript, so the two cannot diverge;
only the preamble, paths, bibliography style and appendix heading differ.
"""
import pathlib, re
AQUI = pathlib.Path(__file__).resolve().parent
PRE = r"""% ============================================================================
% papers/attention-selective-ner/cl/main.tex -- Computational Linguistics version
% ----------------------------------------------------------------------------
% Target (author decision, 2026-09-28): Computational Linguistics, short paper
% (15-25 journal pages of main content, excluding acknowledgements, references
% and appendices; abstract 150-250 words; NOT double-blind: names and
% affiliations on page one). Class: clv2025.cls (downloaded 2026-09-28 from
% submissions.cljournal.org/stylefiles; identical to the 2025-01-01 file checked
% 2026-10-06). Front matter, \pageonefooter, \appendixsection and the compling.bst
% bibliography style follow COLI_template.tex. Body identical to ../main.tex.
% Every result is a macro from ../numeros.tex. Do not type a result here.
% ============================================================================
\documentclass[final]{clv2025}
\jvol{vv}
\jnum{nn}
\jyear{2026}
\dochead{Short Paper}
\pageonefooter{Action editor: \{action editor name\}. Submission received: DD Month YYYY; revised version received: DD Month YYYY; accepted for publication: DD Month YYYY.}
\runningtitle{Shadows on the Cave Wall}
\runningauthor{Souza, Miranda e Silva, Espíndola, and Cerqueira}

\usepackage{amsmath,amssymb,mathtools}
\usepackage{graphicx}
\graphicspath{{../img/}}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{float}
\usepackage[dvipsnames]{xcolor}
\usepackage[capitalise]{cleveref}
% the class sets an 8-bit Palatino; map the few characters it lacks
\usepackage{newunicodechar}
\newunicodechar{ć}{\'c}
\newunicodechar{Š}{\v{S}}
\newunicodechar{—}{---}
\newunicodechar{–}{--}
\newunicodechar{−}{\ensuremath{-}}
\newcommand{\gliner}{GLiNER}
\newcommand{\aurc}{\textsc{aurc}}
\newcommand{\authornote}[1]{\textcolor{BrickRed}{\textbf{[Open decision:} #1\textbf{]}}}
\input{../numeros}
\input{../numeros_nulo}
\input{../publicacao}

\begin{document}
\title{Shadows on the Cave Wall: What Attention Says About Extraction Errors Is Mostly Geometry}
\author{Anaximandro Souza\thanks{Corresponding author}$^{,1,2}$, João Victor de Oliveira Miranda e Silva$^{2}$, Rogério Pinto Espíndola$^{1}$, Renato Cerqueira$^{2}$}
\affilblock{
    \affil{PEC/COPPE, Universidade Federal do Rio de Janeiro (UFRJ)\\\quad \email{anaximandro.souza@coc.ufrj.br}}
    \affil{PUC-Behring Institute for AI}
}
\maketitle

"""
src = (AQUI.parent / "main.tex").read_text(encoding="utf-8")
body = src[src.index("\\begin{abstract}"):]
body = body.replace("img/fig_", "fig_")
import re as _re
body = _re.sub(r"\\input\{(tab_[A-Za-z_]+)\}", r"\\input{../\1}", body)
body = body.replace("\\bibliographystyle{plainnat}\n\\bibliography{references}",
                    "\\bibliographystyle{compling}\n\\bibliography{referencias_cl}")
# compling.bst (the journal's style) prints `note`, where the shared bibliography keeps reading
# notes: write a copy without `note`, giving arXiv-only @misc entries a howpublished line instead.
_fonte = AQUI.parent / "references.bib"  # the released copy (artigo/references.bib)
if not _fonte.exists():  # the authors' tree keeps one bibliography for all papers
    _fonte = AQUI.parent.parent.parent.joinpath("shared", "references.bib")
_bib = _fonte.read_text(encoding="utf-8")
def _limpa(ent):
    ent = re.sub(r"\n\s*note\s*=\s*(\{(?:[^{}]|\{[^{}]*\})*\}|\"[^\"]*\")\s*,?", "", ent)
    if re.match(r"@misc", ent, re.I) and not re.search(r"howpublished\s*=", ent, re.I):
        m = re.search(r"eprint\s*=\s*[{\"]([^}\"]+)", ent)
        if m:
            ent = re.sub(r",?\s*\}\s*$", f",\n  howpublished = {{arXiv:{m.group(1)}}}\n}}", ent.rstrip())
    return ent
_ents = re.split(r"(?=^@)", _bib, flags=re.M)
(AQUI / "referencias_cl.bib").write_text("% generated by gerar_cl.py (note fields removed)\n"
    + "\n".join(_limpa(e) if e.startswith("@") else "" for e in _ents), encoding="utf-8")
_i = body.index("\\appendix")
body = body[:_i] + body[_i:].replace("\\section{", "\\appendixsection{")
# \appendixsection is a starred section, so \label cannot pick up its letter: write the letters in.
_labs = re.findall(r"\\appendixsection\{[^}]*\}\s*\\label\{([^}]+)\}", body)
for _n, _lab in enumerate(_labs):
    for _c in ("\\cref{", "\\Cref{"):
        body = body.replace(_c + _lab + "}", "Appendix~" + chr(65 + _n))
    body = body.replace("Appendix~\\ref{" + _lab + "}", "Appendix~" + chr(65 + _n))
    body = body.replace("\\ref{" + _lab + "}", chr(65 + _n))
body = re.sub(r"\\paragraph\{([^{}]*?)\.\}", r"\\paragraph{\1}", body)   # the class adds the period
body = re.sub(r"\\paragraph\{([^{}]*?)\.''\}", r"\\paragraph{\1''}", body)
(AQUI / "main.tex").write_text(PRE + body, encoding="utf-8")
print("cl/main.tex written")
