"""Numerical check of the two references (eq. null and eq. nullcausal) for the manuscript.

    python verificar_nulo.py [<attention-selective-ner>]

Writes `numeros_nulo.tex`. Uses the repository's own MEASUREMENT functions
(`span_attention_mass`, `causal_mass`) and its own DERIVED references
(`expected_mass`, `expected_mass_causal`), so what is checked is the pair the
analysis actually uses, not a re-implementation.

The check: draw one attention tensor whose rows are far from uniform (gamma
weights, shape 0.5), then permute, independently in every row, the weights
among the keys that row may see. Permutation is exactly the "indifferent model"
of the paper: every row keeps its values, only which keys hold them changes. The
mean measured mass of a fixed span over the permutations must match the derived
reference within Monte Carlo error. We report the largest deviation in standard
errors over all configurations.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import numpy as np

AQUI = Path(__file__).resolve().parent
REPO = Path(sys.argv[1] if len(sys.argv) > 1 else os.environ.get(
    "ASNER_REPO", AQUI.parent if (AQUI.parent / "src" / "selective").exists()
    else AQUI.parents[3] / "attention-selective-ner"))
sys.path.insert(0, str(REPO))
from src.selective.attention_mass import span_attention_mass  # noqa: E402
from src.selective.geometry import causal_mass, expected_mass, expected_mass_causal  # noqa: E402

N_PERM, SEED, L, H = 1000, 11, 2, 2
rng = np.random.default_rng(SEED)


def tensor(T: int, causal: bool) -> np.ndarray:
    a = rng.gamma(shape=0.5, scale=1.0, size=(L, H, T, T)) + 1e-12
    if causal:
        a = a * np.tril(np.ones((T, T)))
    return a / a.sum(axis=-1, keepdims=True)


def permute(A0: np.ndarray, causal: bool) -> np.ndarray:
    A = np.empty_like(A0)
    T = A0.shape[-1]
    for l in range(L):
        for h in range(H):
            for i in range(T):
                n = i + 1 if causal else T
                A[l, h, i, :n] = A0[l, h, i, rng.permutation(n)]
                A[l, h, i, n:] = 0.0
    return A


def verify(configs, causal: bool):
    out = []
    for T, a, k in configs:
        A0 = tensor(T, causal)
        idx = list(range(a, a + k))
        m = []
        for _ in range(N_PERM):
            A = permute(A0, causal)
            m.append(causal_mass(A, idx) if causal
                     else span_attention_mass(A, idx, sink_policy="keep").mass)
        m = np.asarray(m)
        der = float(expected_mass_causal(a, k, T)) if causal else float(expected_mass(k, T, sink_policy="keep"))
        se = m.std(ddof=1) / np.sqrt(len(m))
        out.append(dict(T=T, a=a, k=k, obs=float(m.mean()), der=der, z=abs(m.mean() - der) / se))
    return out


BID = [(20, 3, 2), (40, 10, 1), (40, 5, 4), (60, 30, 6)]
CAU = [(20, 3, 2), (40, 0, 1), (40, 30, 4), (60, 45, 4)]
b, c = verify(BID, False), verify(CAU, True)
for r in b + c:
    print(r)

M = {
    "nullPerm": f"{N_PERM:,}",
    "nullConfigs": str(len(BID) + len(CAU)),
    "nullBidMaxZ": f"{max(r['z'] for r in b):.1f}",
    "nullCauMaxZ": f"{max(r['z'] for r in c):.1f}",
    # illustration of eq. nullcausal: position dominates size under a causal mask
    "exCausalStartOne": f"{float(expected_mass_causal(0, 1, 60)):.3f}",
    "exCausalEndFour": f"{float(expected_mass_causal(45, 4, 60)):.3f}",
    "exBidOne": f"{float(expected_mass(1, 60, sink_policy='keep')):.3f}",
    "exBidFour": f"{float(expected_mass(4, 60, sink_policy='keep')):.3f}",
}
with (AQUI / "numeros_nulo.tex").open("w", encoding="utf-8") as fh:
    fh.write("% GENERATED by verificar_nulo.py. Do not edit.\n")
    for k_, v in M.items():
        fh.write(f"\\newcommand{{\\{k_}}}{{{v}}}\n")
print(M)
